### ISSUE TITLE
demo 跑不起来

### ISSUE THREAD

**Issue by jiangkaiying** [samlss/KeyStore#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iigo.keystore/com.iigo.keystore.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PrivateKey java.security.KeyStore$PrivateKeyEntry.getPrivateKey()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PrivateKey java.security.KeyStore$PrivateKeyEntry.getPrivateKey()' on a null object reference
        at com.iigo.keystore.KeyStoreUtil.sign(KeyStoreUtil.java:246)
        at com.iigo.keystore.MainActivity.onCreate(MainActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by MaosanDao** [comment]
me too
